### ISSUE TITLE
Paper Review: Unit test documentation

### ISSUE THREAD

**Issue by joeweaver** [mjacob1002/Eir#9]
Minor edit, but it would be nice to have a brief (1-2 sentences) on how to kick off the unit tests.

It looks like you're comparing results against pre-generated CSVs.  Are the data in those CSVs a 'gold standard' for these models, or are they to prevent regressions within your own implementations?  Either is fine, I'd just prefer to have that documented somewhere.

**Comment by mjacob1002** [comment]
Hi @joeweaver,

Because of the stochasticity of the package, in order to have consistency, I seeded the numpy RNG and then documented the outputs of that particular seed and wrote it to a CSV file. This would allow for there to be a correct output to check against. I'll document it in the docs folder.

**Comment by joeweaver** [comment]
The updated docs clear up what the tests are doing.
